# Generated by Django 2.1.5 on 2019-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='challenge_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
