# Generated by Django 2.1.5 on 2019-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackme', '0002_auto_20190210_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='challenge_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_data',
            field=models.CharField(default='', max_length=255),
        ),
    ]
